import type { FeedGroup } from '~/types/feed'
import { getGhAvatar } from './utils/img'

export default [{
    name: '网上邻居',
    desc: '哔——啵——电波通讯中，欢迎常来串门。',
    entries: [{
        author: 'L1nSn0w',
        title: 'L1nSn0w\'s Site',
        desc: '无限进步.🎈',
        link: 'https://linsnow.cn/',
        feed: 'https://linsnow.cn/index.xml',
        icon: 'https://unavatar.webp.se/linsnow.cn?w',
        avatar: getGhAvatar('lin-snow'),
        archs: ['Hugo', '服务器'],
        date: '2024-02-14',
        comment: '广工学弟。',
    }, {
        author: '清羽飞扬',
        title: 'LiuShen\'s Blog',
        desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
        link: 'https://blog.liushen.fun/',
        feed: 'https://blog.liushen.fun/atom.xml',
        icon: 'https://blog.liushen.fun/info/avatar.ico',
        avatar: 'https://weavatar.com/avatar/92c15d4a1d99a8ee04b986a14a5f7e009e574b3383fc575005947988ccf205e2',
        archs: ['Hexo', '国内 CDN'],
        date: '2024-06-02',
        comment: '武理工学长，西安老乡。',
    }, {
        author: '天翔TNXG',
        sitenick: '空间站',
        title: '天翔TNXGの空间站',
        desc: '明日尚未到来，希望凝于心上',
        link: 'https://tnxgmoe.com/',
        feed: 'https://tnxgmoe.com/feed',
        icon: 'https://tnxgmoe.com/favicon.png',
        avatar: 'https://api-space.tnxg.top/avatar?s=qq',
        archs: ['Mix Space', 'Cloudflare'],
        date: '2024-07-11',
        comment: '西北地区高中生，开源爱好者。',
    },{
        author: 'FloatSheep',
        title: 'FloatSheep\'s Blog',
        desc: 'On the other side of obstacles',
        link: 'https://blog.hesiy.cn/',
        feed: 'https://blog.hesiy.cn/posts/index.xml',
        icon: 'https://blog.hesiy.cn/favicon.ico',
        avatar: getGhAvatar('FloatSheep'),
        archs: ['Hugo', 'Deno Deploy'],
        date: '2024-07-24',
        comment: '喜欢折腾。',
    },{
        author: 'Redish101',
        title: 'Redish101 Blog',
        desc: '学生，人，活的',
        link: 'https://blog.redish101.top/',
        feed: 'https://blog.redish101.top/feed',
        icon: getGhAvatar('Redish101', { preset: 'icon' }),
        avatar: getGhAvatar('Redish101'),
        archs: ['Next.js', 'Vercel'],
        date: '2024-10-27',
        comment: '江湖人称数据库，初中生，博客开发中。',
    }, {
        author: '葱苓',
        sitenick: '语畔',
        title: '葱苓语畔',
        desc: 'Don\'t worry, be happy.',
        link: 'https://blog.ciraos.top/',
        feed: 'https://blog.ciraos.top/feed.xml',
        icon: 'https://blog.ciraos.top/avatar.avif',
        avatar: 'https://blog.ciraos.top/avatar.avif',
        archs: ['Next.js', '国内 CDN'],
        date: '2025-03-28',
        comment: '前端学习。',
    }],
}] satisfies FeedGroup[]
